### ISSUE TITLE
Using NodeSession with iisnode

### ISSUE THREAD

**Issue by miljosh68** [quorrajs/NodeSession#10]
I am interested in using NodeSession with following configuration: 
iisnode version is 0.2.21, 
node version is v10.7.0, 
express version 4.16.3

My code is as follows: 

```
// express
var express = require('express');
var app = express();

// path
var path = require('path');

// session management
var NodeSession = require('node-session');
session = new NodeSession({secret: 'mysecretkeygoeshere'});
session.startSession(req, res, callback);
```

I am not sure where I should put the line 'session.startSession(req, res, callback)', it throws error showing "'req' is undefined".

**Comment by harishanchu** [comment]
Please refer to this example https://github.com/quorrajs/NodeSession/blob/master/examples/express.js to use this library with express js.

Hope it helps.
