### ISSUE TITLE
Integrating with Express

### ISSUE THREAD

**Issue by koxu1996** [quorrajs/NodeSession#7]
I tried to make node-session work along with express:
```
var express = require('express')
var NodeSession = require('node-session');

var session = new NodeSession({secret: 'Q3UBzdH9GEfiRCTKbi5MTPyChpzXLsTD'});
var app = express()

app.use(function (req, res, next) {
    session.startSession(req, res, function() {})

    // count the views
    req.session.put('views', (req.session.get('views') || 0) + 1)

    next()
})

app.get('/', function (req, res, next) {
    res.send('you viewed this page ' + req.session.get('views') + ' times')
})

app.listen(3000, () => console.log('Example app listening on port 3000!'))
```
But data from session is not loaded and very time I see "you viewed this page 1 times".

Could you tell what is wrong or is it issue?

**Comment by harishanchu** [comment]
You are adding values to the session even before session is started.

Once you call the startSession method continue the rest of the operation inside it's callback.

ie., your code should be changed like below.

```
app.use(function (req, res, next) {
    session.startSession(req, res, function() {
        // count the views
        req.session.set('views', req.session.get('views', 0) + 1);

        next();
    });
})
```


Please refer this example https://github.com/quorrajs/NodeSession/blob/master/examples/express.js

**Comment by koxu1996** [comment]
Thank you for response, example is perfect!

BTW I think it should be mentioned that key should not contain characters like /, \, *.
